CREATE DATABASE M01I12
ON PRIMARY (
    NAME = 'M01I12.MDF';
    FILENAME = 'C:\DB\M01I12.MDF'
)LOG ON(
    NAME = 'M01I12.LDF';
    FILENAME = 'C:\DB\M01I12.LDF';
)
GO
USE M01I12
GO

CREATE TABLE Mtto_P_T_Ele(
    id INT AUTO_INCREMENT PRIMARY KEY,
    status BOOLEAN,
    no_P VARCHAR(20) NOT NULL,
    date DATE,
    ubi VARCHAR(20) NOT NULL,
    no_board VARCHAR(20) NOT NULL,
    no_emp VARCHAR(20) NOT NULL,
    q1 VARCHAR(5) NOT NULL,
    q1_def VARCHAR(5) NOT NULL,
    q1_def_desc VARCHAR(100) NOT NULL,
    q2 VARCHAR(5) NOT NULL,
    q2_def VARCHAR(5) NOT NULL,
    q2_def_desc VARCHAR(100) NOT NULL,
    q3 VARCHAR(5) NOT NULL,
    q3_def VARCHAR(5) NOT NULL,
    q3_def_desc VARCHAR(100) NOT NULL,
    q4 VARCHAR(5) NOT NULL,
    q4_def VARCHAR(5) NOT NULL,
    q4_def_desc VARCHAR(100) NOT NULL,
    q5 VARCHAR(5) NOT NULL,
    q5_def VARCHAR(5) NOT NULL,
    q5_def_desc VARCHAR(100) NOT NULL,
    q6 VARCHAR(5) NOT NULL,
    q6_def VARCHAR(5) NOT NULL,
    q6_def_desc VARCHAR(100) NOT NULL,
    q7 VARCHAR(5) NOT NULL,
    q7_def VARCHAR(5) NOT NULL,
    q7_def_desc VARCHAR(100) NOT NULL,
    q8 VARCHAR(5) NOT NULL,
    q8_def VARCHAR(5) NOT NULL,
    q8_def_desc VARCHAR(100) NOT NULL,
    q9 VARCHAR(5) NOT NULL,
    q9_def VARCHAR(5) NOT NULL,
    q9_def_desc VARCHAR(100) NOT NULL,
    q10 VARCHAR(5) NOT NULL,
    q10_def VARCHAR(5) NOT NULL,
    q10_def_desc VARCHAR(100) NOT NULL,
    q11 VARCHAR(5) NOT NULL,
    q11_def VARCHAR(5) NOT NULL,
    q11_def_desc VARCHAR(100) NOT NULL,
    q12 VARCHAR(5) NOT NULL,
    q12_def VARCHAR(5) NOT NULL,
    q12_def_desc VARCHAR(100) NOT NULL,
    q13 VARCHAR(5) NOT NULL,
    q13_def VARCHAR(5) NOT NULL,
    q13_def_desc VARCHAR(100) NOT NULL,
    q14 VARCHAR(5) NOT NULL,
    q14_def VARCHAR(5) NOT NULL,
    q14_def_desc VARCHAR(100) NOT NULL,
    q15 VARCHAR(5) NOT NULL,
    q15_def VARCHAR(5) NOT NULL,
    q15_def_desc VARCHAR(100) NOT NULL,
    q16 VARCHAR(5) NOT NULL,
    q16_def VARCHAR(5) NOT NULL,
    q16_def_desc VARCHAR(100) NOT NULL,
    q17 VARCHAR(5) NOT NULL,
    q17_def VARCHAR(5) NOT NULL,
    q17_def_desc VARCHAR(100) NOT NULL,
    q18 VARCHAR(5) NOT NULL,
    q18_def VARCHAR(5) NOT NULL,
    q18_def_desc VARCHAR(100) NOT NULL,
    q19 VARCHAR(5) NOT NULL,
    q19_def VARCHAR(5) NOT NULL,
    q19_def_desc VARCHAR(100) NOT NULL,
    q20 VARCHAR(5) NOT NULL,
    q20_def VARCHAR(5) NOT NULL,
    q20_def_desc VARCHAR(100) NOT NULL,
    q21 VARCHAR(5) NOT NULL,
    q21_def VARCHAR(5) NOT NULL,
    q21_def_desc VARCHAR(100) NOT NULL,
    q22 VARCHAR(5) NOT NULL,
    q22_def VARCHAR(5) NOT NULL,
    q22_def_desc VARCHAR(100) NOT NULL,
    q23 VARCHAR(5) NOT NULL,
    q23_def VARCHAR(5) NOT NULL,
    q23_def_desc VARCHAR(100) NOT NULL,
    q24 VARCHAR(5) NOT NULL,
    q24_def VARCHAR(5) NOT NULL,
    q24_def_desc VARCHAR(100) NOT NULL,
    q25 VARCHAR(5) NOT NULL,
    q25_def VARCHAR(5) NOT NULL,
    q25_def_desc VARCHAR(100) NOT NULL,
    observation_Tec VARCHAR(100),
    observation_Sup VARCHAR(100),
    tecnic INT,
    supervisor INT,
    desc_Rep VARCHAR(100),
    quantity_Rep INT,
    no_Parte_Rep VARCHAR(100),
    repairman_Rep INT,
    sup_Rep INT
);

CREATE TABLE Insp_Ba(
    id_Insp_Ba INT AUTO_INCREMENT PRIMARY KEY,
    banos VARCHAR (100),
    area VARCHAR (100),
    date DATE,
    q1 VARCHAR(5), 
    q1_def VARCHAR(5),
    q1_def_desc VARCHAR(100),
    q2 VARCHAR(5),
    q2_def VARCHAR(5),
    q2_def_desc VARCHAR(100),
    q3 VARCHAR(5),
    q3_def VARCHAR(5),
    q3_def_desc VARCHAR(100),
    q4 VARCHAR(5),
    q4_def VARCHAR(5),
    q4_def_desc VARCHAR(100),
    q5 VARCHAR(5),
    q5_def VARCHAR(5),
    q5_def_desc VARCHAR(100),
    q6 VARCHAR(5),
    q6_def VARCHAR(5),
    q6_def_desc VARCHAR(100),
    q7 VARCHAR(5),
    q7_def VARCHAR(5),
    q7_def_desc VARCHAR(100),
    q8 VARCHAR(5),
    q8_def VARCHAR(5),
    q8_def_desc VARCHAR(100),
    q9 VARCHAR(5),
    q9_def VARCHAR(5),
    q9_def_desc VARCHAR(100),
    q10 VARCHAR(5),
    q10_def VARCHAR(5),
    q10_def_desc VARCHAR(100),
    q11 VARCHAR(5),
    q11_def VARCHAR(5),
    q11_def_desc VARCHAR(100),
    observation_Tec VARCHAR(100),
    observation_Sup VARCHAR(100),
    tecnic INT,
    supervisor INT,
    desc_Rep VARCHAR(100),
    quantity_Rep INT,
    no_Parte VARCHAR(20),
    repairman INT,
    sup_Rep INT,
    status BOOLEAN
);